name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: devops-projects-04
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        cd devops-projects-04
        npm install
    - name: Build
      run: |
        cd devops-projects-04
        npm run build --if-present

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: devops-projects-04
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: |
        cd devops-projects-04
        npm install
    - name: Test
      run: |
        cd devops-projects-04
        npm test